---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Public website for the Bovi-Analytics lab

[Miel Hostens](https://www.bovi-analytics.com/) • Faculty of Veterinary Medicine • Utrecht University

## How to build the site

1.  Install [RStudio](https://www.rstudio.com/products/rstudio/download/#download) version 2022.07.1 or later since it has a [Quarto](https://quarto.org/) installation embedded in it. Otherwise, download and install [Quarto](https://quarto.org/) separately.
2. Make sure to have R tools installed.
2.  Open `bovi-analytics.Rproj` to open an [RStudio Project](https://r4ds.had.co.nz/workflow-projects.html).
3.  If it's not installed already, R *should* try to install the [{renv} package](https://rstudio.github.io/renv/) when you open the RStudio Project for the first time. If you don't see a message about package installation, install it yourself by running `install.packages("renv")` in the R console.
4. I had to run `renv::equip()` first to install some tools
5. Then renv::activate() -> re
5. Make sure you update the lock file to the correct r version
5.  Run `renv::restore()` in the R console to install all the required packages for this project.
6.  `r emoji::emoji("tada")` All done! `r emoji::emoji("tada")` The complete website will be in a folder named `_site/`.

```{bash}
quarto publish gh-pages --no-browser --no-prompt	
```

The pipeline does major tasks:

-   **Build Quarto website**: This project is a [Quarto website](https://quarto.org/docs/websites/), which compiles and stitches together all the `.qmd` files in this project based on the settings in [`_quarto.yml`](_quarto.yml). See the [Quarto website documentation](https://quarto.org/docs/websites/) for more details.

-   **Upload resulting `_site/` folder to github pages**: This project is published using github pages using the `quarto publish gh-pages --no-browser` command

## Licenses

**Text and figures:** All prose and images are licensed under Creative Commons ([CC-BY-NC 4.0](https://creativecommons.org/licenses/by-nc/4.0/))

**Code:** All code is licensed under the [MIT License](LICENSE.md).

## Issues

If ' 'gh-pages' is already checked out' error occurs -\> remove any folder in the .git/worktree folder
