---
title: "What is Slack, and why Slack?"
execute:
  eval: false
categories:
  - Slack
authors: Miel Hostens, et al.
date: 08/02/23
toc: true
---

# Introduction

Slack is a cloud-based collaboration and communication platform designed for teams and businesses. It is primarily used for workplace communication, enabling teams to collaborate, share information, and stay connected in real-time. Slack provides a centralized space where users can send messages, share files, and integrate with various third-party apps and services.It became popular before microsoft introduced Teams, hence we created the Bovi-Analytics workspace.

## Key features of Slack:

1.  **Channels:** Slack organizes conversations into channels, which can be either public (accessible to all team members) or private (restricted to selected members). This allows teams to keep discussions focused and organized based on different projects, departments, or topics.

2.  **Real-Time Messaging:** Slack offers instant messaging functionality, allowing team members to send and receive messages in real time. This fosters quick and efficient communication within the team.

3.  **File Sharing:** Users can share files and documents directly within Slack, making it easy to collaborate on projects and exchange information without having to switch between different tools.

4.  **Integrations:** Slack integrates with a wide range of third-party apps and services, such as Google Drive, Trello, GitHub, Jira, and more. These integrations enable users to receive updates, notifications, and information from other tools directly within Slack.

5.  **Search and Archive:** Slack retains a searchable archive of all messages and files shared within the platform, making it easy to find and refer back to past conversations and information.

6.  **Notifications:** Slack provides customizable notifications, allowing users to stay informed about important messages, mentions, or activities.

7.  **Bots and Automation:** Slack supports bots and automation, enabling teams to create custom workflows and automate repetitive tasks.

8.  **Voice and Video Calls:** Slack includes voice and video calling capabilities, allowing users to have audio and video meetings directly within the platform.

Slack has become a popular tool for remote and distributed teams, as it facilitates seamless communication and collaboration across different time zones and locations. It is widely used across various industries and organizations, ranging from startups and small businesses to large enterprises.

## Slack notifications to a Bovi-Analytics channel in your pipeline

### Install drivers to your notebook

``` python
# prompt: Send a message to slack channel

!pip install slack_sdk
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError
```

### Create slack-api client with token

``` python
client = WebClient(token='xoxb-35507772116-7431970780242-1Kr19xKdNhqJOZraeIq9CxOn')
```

### Create message and send it

``` python
try:
    response = client.chat_postMessage(
        channel='pushnotifications',
        text="Rsync succesfully synched gdrive to azure"
    )
    print(response)

except SlackApiError as e:
    # You will get a SlackApiError if "ok" is False
    assert e.response["error"]  # e.g., 'invalid_auth', 'channel_not_found'
    print(e)
```
